import { IntegrationMetadata } from './integrationSchema'
import { basePath } from './basePath'

export const INTEGRATIONS: IntegrationMetadata[] = [
  // REFERENCE / PLATFORM
  {
    id: 'github',
    name: 'GitHub',
    category: 'Reference / Platform',
    description: 'Access GitHub repositories, issues, pull requests, and code search via the official MCP server.',
    functionality_type: 'Source Control & Collaboration',
    fields: [
      {
        name: 'token',
        label: 'Personal Access Token',
        type: 'password',
        required: true,
        placeholder: 'ghp_...',
        helpText: 'Generate at GitHub → Settings → Developer settings → Personal access tokens → Tokens (classic). Recommended scopes: repo, workflow, read:org, read:user, user:email.',
      },
    ],
    docs_url: 'https://docs.github.com/en/rest',
  },

  // THREAT INTELLIGENCE
  {
    id: 'virustotal',
    name: 'VirusTotal',
    category: 'Threat Intelligence',
    description: 'Check file hashes, URLs, domains, and IPs against VirusTotal\'s threat intelligence database.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your VirusTotal API key',
        helpText: 'Get your API key from https://www.virustotal.com/gui/my-apikey',
      },
    ],
    docs_url: 'https://developers.virustotal.com/reference/overview',
  },
  {
    id: 'alienvault-otx',
    name: 'AlienVault OTX',
    category: 'Threat Intelligence',
    description: 'Access threat intelligence from AlienVault Open Threat Exchange.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your AlienVault OTX API key',
        helpText: 'Get your API key from https://otx.alienvault.com/api',
      },
    ],
    docs_url: 'https://otx.alienvault.com/api',
  },
  {
    id: 'shodan',
    name: 'Shodan',
    category: 'Threat Intelligence',
    description: 'Search for internet-connected devices and gather intelligence on IP addresses.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your Shodan API key',
        helpText: 'Get your API key from https://account.shodan.io/',
      },
    ],
    docs_url: 'https://developer.shodan.io/',
  },
  {
    id: 'misp',
    name: 'MISP',
    category: 'Threat Intelligence',
    description: 'Connect to MISP (Malware Information Sharing Platform) for threat sharing.',
    functionality_type: 'Data Enrichment',
    proxy_supported: true,
    fields: [
      {
        name: 'url',
        label: 'MISP Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://misp.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your MISP API key',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.misp-project.org/documentation/',
  },
  {
    id: 'gcp-threat-intel',
    name: 'Google Threat Intelligence',
    category: 'Threat Intelligence',
    description: 'Google Threat Intelligence (powered by VirusTotal/Mandiant) for file, URL, domain, and IP reputation lookups, threat actor profiles, and campaign tracking.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'VirusTotal API Key',
        type: 'password',
        required: true,
        placeholder: 'Your VirusTotal API key',
        helpText: 'Uses your VirusTotal API key for Google Threat Intelligence queries. Get one at virustotal.com.',
      },
    ],
    docs_url: 'https://cloud.google.com/threat-intelligence/docs',
  },
  {
    id: 'url-analysis',
    name: 'URL Analysis',
    category: 'Threat Intelligence',
    description: 'Analyze suspicious URLs for phishing, malware, and other threats.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'service',
        label: 'Analysis Service',
        type: 'select',
        required: true,
        default: 'urlscan',
        options: [
          { value: 'urlscan', label: 'URLScan.io' },
          { value: 'google_safe_browsing', label: 'Google Safe Browsing' },
        ],
      },
    ],
    docs_url: 'https://urlscan.io/docs/api/',
  },
  {
    id: 'ip-geolocation',
    name: 'IP Geolocation',
    category: 'Threat Intelligence',
    description: 'Get geolocation data for IP addresses.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'service',
        label: 'Geolocation Service',
        type: 'select',
        required: true,
        default: 'ipapi',
        options: [
          { value: 'ipapi', label: 'IP-API.com (Free)' },
          { value: 'maxmind', label: 'MaxMind GeoIP2' },
        ],
      },
    ],
    docs_url: 'https://ip-api.com/docs',
  },

  // EDR/XDR PLATFORMS
  {
    id: 'crowdstrike',
    name: 'CrowdStrike Falcon',
    category: 'EDR/XDR',
    description: 'Connect to CrowdStrike Falcon for endpoint detection and response with threat intelligence.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'Your CrowdStrike client ID',
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
        placeholder: 'Your CrowdStrike client secret',
      },
      {
        name: 'base_url',
        label: 'Base URL',
        type: 'url',
        required: true,
        default: 'https://api.crowdstrike.com',
        helpText: 'Usually https://api.crowdstrike.com or region-specific endpoint',
      },
    ],
    docs_url: 'https://www.crowdstrike.com/blog/tech-center/get-access-falcon-apis/',
  },
  {
    id: 'sentinelone',
    name: 'SentinelOne',
    category: 'EDR/XDR',
    description: 'Integrate with SentinelOne for autonomous endpoint protection with AI-powered threat detection.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'API URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-instance.sentinelone.net',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        placeholder: 'Your SentinelOne API token',
      },
    ],
    docs_url: 'https://usea1-partners.sentinelone.net/docs/en/using-api-tokens.html',
  },
  {
    id: 'carbon-black',
    name: 'VMware Carbon Black',
    category: 'EDR/XDR',
    description: 'Connect to VMware Carbon Black Cloud for endpoint security and threat hunting.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'url',
        label: 'Carbon Black URL',
        type: 'url',
        required: true,
        placeholder: 'https://defense.conferdeploy.net',
      },
      {
        name: 'api_id',
        label: 'API ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_key',
        label: 'API Secret Key',
        type: 'password',
        required: true,
      },
      {
        name: 'org_key',
        label: 'Organization Key',
        type: 'text',
        required: true,
      },
    ],
    docs_url: 'https://developer.carbonblack.com/',
  },
  {
    id: 'microsoft-defender',
    name: 'Microsoft Defender for Endpoint',
    category: 'EDR/XDR',
    description: 'Integrate with Microsoft Defender for Endpoint (MDE) for enterprise endpoint protection.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
        placeholder: 'Your Azure AD tenant ID',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'Application (client) ID',
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api-hello-world',
  },
  {
    id: 'cortex-xdr',
    name: 'Cortex XDR (Palo Alto)',
    category: 'EDR/XDR',
    description: 'Palo Alto Networks Cortex XDR for extended detection and response across endpoints, networks, and clouds.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'Cortex XDR API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api-<fqdn>',
        helpText: 'Your Cortex XDR tenant API URL',
      },
      {
        name: 'api_key_id',
        label: 'API Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR/Cortex-XDR-API-Reference',
  },
  {
    id: 'trend-micro-vision-one',
    name: 'Trend Micro Vision One',
    category: 'EDR/XDR',
    description: 'Trend Micro Vision One XDR platform for comprehensive threat detection and response.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'Vision One API URL',
        type: 'select',
        required: true,
        options: [
          { value: 'https://api.xdr.trendmicro.com', label: 'US' },
          { value: 'https://api.eu.xdr.trendmicro.com', label: 'EU' },
          { value: 'https://api.in.xdr.trendmicro.com', label: 'India' },
          { value: 'https://api.au.xdr.trendmicro.com', label: 'Australia' },
          { value: 'https://api.sg.xdr.trendmicro.com', label: 'Singapore' },
        ],
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://automation.trendmicro.com/xdr/home',
  },
  {
    id: 'sophos-intercept-x',
    name: 'Sophos Intercept X',
    category: 'EDR/XDR',
    description: 'Sophos Intercept X with EDR for deep learning AI malware protection and threat hunting.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
        helpText: 'From Sophos Central API credentials',
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: false,
        helpText: 'Organization/Partner tenant ID (if applicable)',
      },
    ],
    docs_url: 'https://developer.sophos.com/',
  },
  {
    id: 'cybereason',
    name: 'Cybereason',
    category: 'EDR/XDR',
    description: 'Cybereason Defense Platform for endpoint protection and proactive threat hunting.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'server_url',
        label: 'Cybereason Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-tenant.cybereason.net',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://nest.cybereason.com/documentation/api-documentation',
  },
  {
    id: 'trellix',
    name: 'Trellix (McAfee)',
    category: 'EDR/XDR',
    description: 'Trellix XDR (formerly McAfee) for unified security operations and threat intelligence.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'Trellix API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.manage.trellix.com',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://developer.trellix.com/',
  },
  {
    id: 'tanium',
    name: 'Tanium',
    category: 'EDR/XDR',
    description: 'Tanium unified endpoint management and security platform for real-time visibility and control.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'server_url',
        label: 'Tanium Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://tanium.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://developer.tanium.com/',
  },
  {
    id: 'cynet',
    name: 'Cynet 360',
    category: 'EDR/XDR',
    description: 'Cynet 360 autonomous breach protection platform with XDR capabilities.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'Cynet API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.cynet.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
    ],
    docs_url: 'https://www.cynet.com/platform/cynet-api/',
  },
  {
    id: 'eset',
    name: 'ESET Inspect',
    category: 'EDR/XDR',
    description: 'ESET Inspect EDR for in-depth threat detection and incident response.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'server_url',
        label: 'ESET PROTECT Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://eset.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://help.eset.com/protect_cloud/en-US/api.html',
  },
  {
    id: 'bitdefender-gravityzone',
    name: 'Bitdefender GravityZone',
    category: 'EDR/XDR',
    description: 'Bitdefender GravityZone for endpoint security and advanced threat prevention.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'GravityZone API URL',
        type: 'url',
        required: true,
        placeholder: 'https://gravityzone.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Generate in Control Center → Network → API Keys',
      },
    ],
    docs_url: 'https://www.bitdefender.com/business/support/en/77209-126992-api.html',
  },
  {
    id: 'fortinet-fortiedr',
    name: 'Fortinet FortiEDR',
    category: 'EDR/XDR',
    description: 'Fortinet FortiEDR for automated real-time endpoint protection and threat response.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'server_url',
        label: 'FortiEDR Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://fortiedr.example.com',
      },
      {
        name: 'organization_id',
        label: 'Organization ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.fortinet.com/product/fortiedr/',
  },
  {
    id: 'kaspersky',
    name: 'Kaspersky EDR',
    category: 'EDR/XDR',
    description: 'Kaspersky Endpoint Detection and Response Optimum for threat detection and investigation.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'ksc_url',
        label: 'Kaspersky Security Center URL',
        type: 'url',
        required: true,
        placeholder: 'https://ksc.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://support.kaspersky.com/KSC/14/en-US/179891.htm',
  },
  {
    id: 'cisco-secure-endpoint',
    name: 'Cisco Secure Endpoint',
    category: 'EDR/XDR',
    description: 'Cisco Secure Endpoint (formerly AMP) for advanced malware protection and endpoint security.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'API URL',
        type: 'select',
        required: true,
        options: [
          { value: 'https://api.amp.cisco.com', label: 'North America' },
          { value: 'https://api.eu.amp.cisco.com', label: 'Europe' },
          { value: 'https://api.apjc.amp.cisco.com', label: 'Asia Pacific' },
        ],
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://api-docs.amp.cisco.com/',
  },
  {
    id: 'symantec-edr',
    name: 'Symantec EDR',
    category: 'EDR/XDR',
    description: 'Symantec Endpoint Detection and Response (formerly EDR Cloud) for threat detection.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'Symantec EDR API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.sep.securitycloud.symantec.com',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://apidocs.securitycloud.symantec.com/',
  },

  // DETECTION & AI
  {
    id: 'loglm',
    name: 'LogLM',
    category: 'Detection & AI',
    description:
      'DeepTempo LogLM anomaly detections stream into Vigil as findings, and the LogLM model-admin panel mounts natively inside the console. Requires the paid, opt-in LogLM connector.',
    functionality_type: 'AI Detection & Model Admin',
    has_ui: true,
    fields: [
      {
        name: 'connectorUrl',
        label: 'Connector URL',
        type: 'url',
        required: true,
        placeholder: 'https://loglm-connector.internal',
        helpText:
          'Base URL of the LogLM connector — it serves the admin UI bundle, the extension manifest, and the session/model APIs. The browser calls this directly, so it must be reachable from the analyst\'s browser with CORS enabled.',
      },
      {
        name: 'mint_secret',
        label: 'Session Mint Secret',
        type: 'password',
        required: true,
        helpText:
          'Shared HMAC secret Vigil uses to request short-lived, user-scoped session tokens from the connector (matches the connector\'s CONNECTOR_BFF_SESSION_MINT_SECRET). Stored encrypted server-side; never sent to the browser.',
      },
      {
        name: 'mcp_token',
        label: 'MCP Bearer Token',
        type: 'password',
        required: true,
        helpText:
          'Static bearer token the LogLM agent tools present to the connector\'s MCP endpoint (matches the connector\'s CONNECTOR_MCP_AUTH_TOKEN). Stored encrypted server-side; never sent to the browser.',
      },
    ],
    docs_url: 'https://docs.deeptempo.ai/loglm',
  },

  // SIEM
  {
    id: 'splunk',
    name: 'Splunk',
    category: 'SIEM',
    description: 'Connect to Splunk Enterprise or Splunk Cloud for log aggregation, search, and analysis with natural language query generation.',
    functionality_type: 'Log Analysis & SIEM',
    has_ui: true,
    proxy_supported: true,
    fields: [
      {
        name: 'server_url',
        label: 'Splunk Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://splunk.example.com:8089',
        helpText: 'Splunk management port (usually 8089)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'admin',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
        helpText: 'Disable for self-signed certificates',
      },
      {
        name: 'lookback_hours',
        label: 'Lookback Hours',
        type: 'number',
        required: false,
        default: 168,
        placeholder: '168',
        helpText: 'Default time range for queries (in hours, default: 168 = 7 days)',
      },
    ],
    docs_url: 'https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog',
  },
  {
    id: 'cribl-stream',
    name: 'Cribl Stream',
    category: 'Data Pipeline',
    description: 'Observability pipeline for collecting, processing, enriching, and routing security data. Normalize logs, reduce volume, and optimize data flow before AI analysis.',
    functionality_type: 'Data Pipeline & Enrichment',
    has_ui: false,
    proxy_supported: true,
    fields: [
      {
        name: 'server_url',
        label: 'Cribl Stream Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://cribl.example.com:9000',
        helpText: 'Cribl Stream API endpoint (usually port 9000)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'admin',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'worker_group',
        label: 'Worker Group',
        type: 'text',
        required: false,
        default: 'default',
        placeholder: 'default',
        helpText: 'Worker group to manage (default: "default")',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
        helpText: 'Disable for self-signed certificates',
      },
    ],
    docs_url: 'https://docs.cribl.io/stream/',
  },
  {
    id: 'elastic-siem',
    name: 'Elastic Security (SIEM)',
    category: 'SIEM',
    description: 'Elastic Security SIEM with advanced analytics, threat hunting, and incident response capabilities.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'elasticsearch_url',
        label: 'Elasticsearch URL',
        type: 'url',
        required: true,
        placeholder: 'https://elasticsearch.example.com:9200',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: false,
        helpText: 'API key for authentication (recommended)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: false,
        helpText: 'Alternative to API key',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: false,
        helpText: 'Required if using username auth',
      },
      {
        name: 'kibana_url',
        label: 'Kibana URL',
        type: 'url',
        required: false,
        placeholder: 'https://kibana.example.com:5601',
        helpText: 'Required for detection alert ingestion and case sync. Leave blank if only using Elasticsearch search.',
      },
      {
        name: 'index_pattern',
        label: 'Alert Index Pattern',
        type: 'text',
        required: false,
        default: '.alerts-security.alerts-default',
        helpText: 'Elasticsearch index pattern for security alerts.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.elastic.co/guide/en/security/current/index.html',
  },
  {
    id: 'azure-sentinel',
    name: 'Microsoft Sentinel',
    category: 'SIEM',
    description: 'Microsoft Azure Sentinel cloud-native SIEM with AI-powered threat detection and response.',
    functionality_type: 'Log Analysis & SIEM',
    fields: [
      {
        name: 'workspace_id',
        label: 'Workspace ID',
        type: 'text',
        required: true,
      },
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/azure/sentinel/',
  },
  {
    id: 'gcp-secops',
    name: 'Google SecOps (Chronicle)',
    category: 'SIEM',
    description: 'Google Security Operations (formerly Chronicle) for cloud-native threat detection, investigation, and response. Query security telemetry with UDM search and detection rules.',
    functionality_type: 'Log Analysis & SIEM',
    fields: [
      {
        name: 'project_id',
        label: 'GCP Project ID',
        type: 'text',
        required: true,
        placeholder: 'my-gcp-project',
        helpText: 'The Google Cloud project ID linked to your Chronicle instance.',
      },
      {
        name: 'customer_id',
        label: 'Chronicle Customer ID',
        type: 'text',
        required: true,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        helpText: 'Your Chronicle customer ID (UUID format).',
      },
      {
        name: 'region',
        label: 'Region',
        type: 'text',
        required: false,
        placeholder: 'us',
        helpText: 'Chronicle region (e.g., us, europe, asia-southeast1). Defaults to us.',
      },
    ],
    docs_url: 'https://cloud.google.com/chronicle/docs',
  },
  {
    id: 'qradar',
    name: 'IBM QRadar',
    category: 'SIEM',
    description: 'IBM QRadar SIEM for enterprise security intelligence and threat detection.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'console_url',
        label: 'QRadar Console URL',
        type: 'url',
        required: true,
        placeholder: 'https://qradar.example.com',
      },
      {
        name: 'sec_token',
        label: 'SEC Token',
        type: 'password',
        required: true,
        helpText: 'Generate in Admin → Authorized Services',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
      },
    ],
    docs_url: 'https://www.ibm.com/docs/en/qsip/7.5?topic=api-restful-api-overview',
  },
  {
    id: 'arcsight',
    name: 'ArcSight (OpenText)',
    category: 'SIEM',
    description: 'OpenText ArcSight ESM for enterprise security event management and correlation.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'manager_url',
        label: 'ArcSight Manager URL',
        type: 'url',
        required: true,
        placeholder: 'https://arcsight.example.com:8443',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.microfocus.com/documentation/arcsight/',
  },
  {
    id: 'logrhythm',
    name: 'LogRhythm',
    category: 'SIEM',
    description: 'LogRhythm SIEM platform with advanced analytics and automated response capabilities.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'api_url',
        label: 'LogRhythm API URL',
        type: 'url',
        required: true,
        placeholder: 'https://logrhythm.example.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Generate in Administration → API Tokens',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.logrhythm.com/',
  },
  {
    id: 'exabeam',
    name: 'Exabeam',
    category: 'SIEM',
    description: 'Exabeam Security Operations Platform with behavioral analytics and UEBA capabilities.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'api_url',
        label: 'Exabeam API URL',
        type: 'url',
        required: true,
        placeholder: 'https://exabeam.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.exabeam.com/',
  },
  {
    id: 'securonix',
    name: 'Securonix',
    category: 'SIEM',
    description: 'Securonix Next-Gen SIEM with advanced threat detection using machine learning and UEBA.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'api_url',
        label: 'Securonix API URL',
        type: 'url',
        required: true,
        placeholder: 'https://securonix.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'tenant',
        label: 'Tenant Name',
        type: 'text',
        required: false,
        helpText: 'Multi-tenant deployment tenant name',
      },
    ],
    docs_url: 'https://documentation.securonix.com/',
  },
  {
    id: 'sumo-logic',
    name: 'Sumo Logic',
    category: 'SIEM',
    description: 'Cloud-native SIEM and log analytics platform with real-time insights and security analytics.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'access_id',
        label: 'Access ID',
        type: 'text',
        required: true,
        helpText: 'Generate in Administration → Security → Access Keys',
      },
      {
        name: 'access_key',
        label: 'Access Key',
        type: 'password',
        required: true,
      },
      {
        name: 'api_endpoint',
        label: 'API Endpoint',
        type: 'select',
        required: true,
        default: 'https://api.sumologic.com/api/',
        options: [
          { value: 'https://api.sumologic.com/api/', label: 'US1 (Prod)' },
          { value: 'https://api.us2.sumologic.com/api/', label: 'US2' },
          { value: 'https://api.eu.sumologic.com/api/', label: 'EU' },
          { value: 'https://api.au.sumologic.com/api/', label: 'AU' },
        ],
      },
    ],
    docs_url: 'https://api.sumologic.com/docs/',
  },
  {
    id: 'graylog',
    name: 'Graylog',
    category: 'SIEM',
    description: 'Open-source log management and SIEM solution for centralized log collection and analysis.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'server_url',
        label: 'Graylog Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://graylog.example.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Generate in System → Users → Edit User → Create Token',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.graylog.org/docs/api',
  },

  // CLOUD SECURITY
  {
    id: 'aws-security-hub',
    name: 'AWS Security Hub',
    category: 'Cloud Security',
    description: 'Integrate with AWS Security Hub for centralized security findings across AWS accounts.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'access_key_id',
        label: 'AWS Access Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'secret_access_key',
        label: 'AWS Secret Access Key',
        type: 'password',
        required: true,
      },
      {
        name: 'region',
        label: 'AWS Region',
        type: 'text',
        required: true,
        default: 'us-east-1',
        placeholder: 'e.g., us-east-1',
      },
    ],
    docs_url: 'https://docs.aws.amazon.com/securityhub/',
  },
  {
    id: 'aws-guardduty',
    name: 'AWS GuardDuty',
    category: 'Cloud Security',
    description: 'AWS intelligent threat detection service for continuous monitoring of malicious activity.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'access_key_id',
        label: 'AWS Access Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'secret_access_key',
        label: 'AWS Secret Access Key',
        type: 'password',
        required: true,
      },
      {
        name: 'region',
        label: 'AWS Region',
        type: 'text',
        required: true,
        default: 'us-east-1',
        placeholder: 'e.g., us-east-1',
      },
      {
        name: 'detector_id',
        label: 'Detector ID',
        type: 'text',
        required: false,
        helpText: 'Optional: Specific GuardDuty detector ID',
      },
    ],
    docs_url: 'https://docs.aws.amazon.com/guardduty/',
  },
  {
    id: 'gcp-security',
    name: 'GCP Security Command Center',
    category: 'Cloud Security',
    description: 'Connect to Google Cloud Security Command Center for centralized security and risk management.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'project_id',
        label: 'Project ID',
        type: 'text',
        required: true,
      },
      {
        name: 'credentials_json',
        label: 'Service Account Credentials (JSON)',
        type: 'password',
        required: true,
        helpText: 'Paste the entire JSON key file content',
      },
    ],
    docs_url: 'https://cloud.google.com/security-command-center/docs',
  },
  {
    id: 'azure-defender',
    name: 'Microsoft Defender for Cloud',
    category: 'Cloud Security',
    description: 'Azure security posture management and threat protection across hybrid cloud workloads.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'subscription_id',
        label: 'Subscription ID',
        type: 'text',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/azure/defender-for-cloud/',
  },
  {
    id: 'prisma-cloud',
    name: 'Prisma Cloud (Palo Alto)',
    category: 'Cloud Security',
    description: 'Comprehensive cloud-native security platform (CNAPP) for multi-cloud environments.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'api_url',
        label: 'Prisma Cloud API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.prismacloud.io',
        helpText: 'Varies by region (api.prismacloud.io, api2.prismacloud.io, etc.)',
      },
      {
        name: 'access_key',
        label: 'Access Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'secret_key',
        label: 'Secret Key',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://prisma.pan.dev/api/cloud/cspm',
  },
  {
    id: 'orca-security',
    name: 'Orca Security',
    category: 'Cloud Security',
    description: 'Agentless cloud security platform for comprehensive visibility and risk assessment.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'api_url',
        label: 'Orca API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.orcasecurity.io',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Generate in Orca Settings → API Tokens',
      },
    ],
    docs_url: 'https://docs.orcasecurity.io/docs/api-documentation',
  },
  {
    id: 'wiz',
    name: 'Wiz',
    category: 'Cloud Security',
    description: 'Cloud security platform for identifying and removing critical risks across multi-cloud environments.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'api_url',
        label: 'Wiz API URL',
        type: 'url',
        required: true,
        placeholder: 'https://api.wiz.io',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.wiz.io/wiz-docs/docs/using-the-wiz-api',
  },
  {
    id: 'lacework',
    name: 'Lacework',
    category: 'Cloud Security',
    description: 'Cloud security platform with anomaly detection and compliance for AWS, Azure, and GCP.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'account',
        label: 'Lacework Account',
        type: 'text',
        required: true,
        placeholder: 'your-account',
        helpText: 'Your Lacework account name (subdomain)',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'text',
        required: true,
      },
      {
        name: 'api_secret',
        label: 'API Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.lacework.net/api',
  },
  {
    id: 'aqua-security',
    name: 'Aqua Security',
    category: 'Cloud Security',
    description: 'Container and cloud-native application security platform for Kubernetes and serverless.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'console_url',
        label: 'Aqua Console URL',
        type: 'url',
        required: true,
        placeholder: 'https://aqua.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.aquasec.com/docs/aqua-api-overview',
  },
  {
    id: 'snyk',
    name: 'Snyk',
    category: 'Cloud Security',
    description: 'Developer security platform for finding and fixing vulnerabilities in code, dependencies, and containers.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Generate in Account Settings → API Token',
      },
      {
        name: 'org_id',
        label: 'Organization ID',
        type: 'text',
        required: false,
        helpText: 'Optional: Default organization for operations',
      },
    ],
    docs_url: 'https://docs.snyk.io/snyk-api-info',
  },

  // IDENTITY & ACCESS
  {
    id: 'okta',
    name: 'Okta',
    category: 'Identity & Access',
    description: 'Integrate with Okta for identity and access management, SSO, and MFA.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'domain',
        label: 'Okta Domain',
        type: 'text',
        required: true,
        placeholder: 'dev-123456.okta.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://developer.okta.com/docs/reference/',
  },
  {
    id: 'authmind',
    name: 'AuthMind',
    category: 'Identity & Access',
    description:
      'Identity-security telemetry from AuthMind: v1 issues and playbooks plus v2 identities, assets, accesses, identity systems, and secrets.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'base_url',
        label: 'API Base URL',
        type: 'url',
        required: true,
        placeholder: 'https://console.authmind.com',
        helpText:
          'Your AuthMind console host (the same hostname you use to log in). /amapi, /amapi/v1, and /amapi/v2 suffixes are all accepted and normalized to /amapi.',
      },
      {
        name: 'api_token',
        label: 'API Token (JWT)',
        type: 'password',
        required: true,
        helpText:
          'Generate under AuthMind Admin → API Tokens. Include `issues` for alerts, `playbooks` for the playbook list, and `posture` for identities/assets/secrets. The token value is shown only once at creation.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL',
        type: 'boolean',
        required: false,
        placeholder: 'true',
      },
    ],
    docs_url: 'https://www.authmind.com',
  },
  {
    id: 'azure-ad',
    name: 'Azure Active Directory',
    category: 'Identity & Access',
    description: 'Connect to Azure AD (Entra ID) for identity management, authentication logs, and conditional access.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/azure/active-directory/',
  },
  {
    id: 'ping-identity',
    name: 'PingIdentity (PingOne)',
    category: 'Identity & Access',
    description: 'PingIdentity platform for enterprise identity and access management solutions.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'environment_id',
        label: 'Environment ID',
        type: 'text',
        required: true,
        helpText: 'PingOne environment identifier',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'region',
        label: 'Region',
        type: 'select',
        required: true,
        default: 'com',
        options: [
          { value: 'com', label: 'North America' },
          { value: 'eu', label: 'Europe' },
          { value: 'asia', label: 'Asia Pacific' },
        ],
      },
    ],
    docs_url: 'https://apidocs.pingidentity.com/pingone/platform/v1/api/',
  },
  {
    id: 'auth0',
    name: 'Auth0',
    category: 'Identity & Access',
    description: 'Auth0 identity platform for authentication and authorization with advanced security features.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'domain',
        label: 'Auth0 Domain',
        type: 'text',
        required: true,
        placeholder: 'your-tenant.auth0.com',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://auth0.com/docs/api',
  },
  {
    id: 'onelogin',
    name: 'OneLogin',
    category: 'Identity & Access',
    description: 'OneLogin unified access management platform for SSO and identity governance.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'region',
        label: 'Region',
        type: 'select',
        required: true,
        options: [
          { value: 'us', label: 'US' },
          { value: 'eu', label: 'EU' },
        ],
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://developers.onelogin.com/api-docs/1/getting-started/dev-overview',
  },
  {
    id: 'duo-security',
    name: 'Duo Security (Cisco)',
    category: 'Identity & Access',
    description: 'Duo multi-factor authentication and secure access platform for zero trust security.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'api_hostname',
        label: 'API Hostname',
        type: 'text',
        required: true,
        placeholder: 'api-xxxxxxxx.duosecurity.com',
      },
      {
        name: 'integration_key',
        label: 'Integration Key',
        type: 'text',
        required: true,
      },
      {
        name: 'secret_key',
        label: 'Secret Key',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://duo.com/docs/adminapi',
  },
  {
    id: 'jumpcloud',
    name: 'JumpCloud',
    category: 'Identity & Access',
    description: 'JumpCloud Directory Platform for unified device and identity management.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Generate in Administrator → API Settings',
      },
      {
        name: 'org_id',
        label: 'Organization ID',
        type: 'text',
        required: false,
        helpText: 'Optional: For multi-org environments',
      },
    ],
    docs_url: 'https://docs.jumpcloud.com/api/1.0/',
  },
  {
    id: 'sailpoint',
    name: 'SailPoint IdentityIQ',
    category: 'Identity & Access',
    description: 'SailPoint enterprise identity governance for access certification and compliance.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'identityiq_url',
        label: 'IdentityIQ URL',
        type: 'url',
        required: true,
        placeholder: 'https://identityiq.example.com',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://documentation.sailpoint.com/',
  },
  {
    id: 'cyberark',
    name: 'CyberArk',
    category: 'Identity & Access',
    description: 'CyberArk Privileged Access Management for securing and managing privileged accounts.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'pvwa_url',
        label: 'PVWA URL',
        type: 'url',
        required: true,
        placeholder: 'https://pvwa.example.com/PasswordVault',
        helpText: 'Password Vault Web Access URL',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'auth_type',
        label: 'Authentication Type',
        type: 'select',
        required: true,
        default: 'CyberArk',
        options: [
          { value: 'CyberArk', label: 'CyberArk' },
          { value: 'LDAP', label: 'LDAP' },
          { value: 'RADIUS', label: 'RADIUS' },
        ],
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/WebServices/Implementing%20Privileged%20Account%20Security%20Web%20Services%20.htm',
  },
  {
    id: 'beyond-trust',
    name: 'BeyondTrust',
    category: 'Identity & Access',
    description: 'BeyondTrust Privileged Access Management and Remote Access solutions.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'api_url',
        label: 'BeyondTrust API URL',
        type: 'url',
        required: true,
        placeholder: 'https://beyondtrust.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.beyondtrust.com/docs/beyondinsight-password-safe/ps/api/index.htm',
  },

  // NETWORK SECURITY
  {
    id: 'palo-alto',
    name: 'Palo Alto Networks',
    category: 'Network Security',
    description: 'Integrate with Palo Alto Networks firewalls and Panorama for policy management and threat prevention.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'hostname',
        label: 'Firewall/Panorama Hostname',
        type: 'text',
        required: true,
        placeholder: 'firewall.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-panorama-api',
  },
  {
    id: 'cisco-firepower',
    name: 'Cisco Firepower',
    category: 'Network Security',
    description: 'Integrate with Cisco Firepower Threat Defense (FTD) and Firepower Management Center (FMC).',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'fmc_host',
        label: 'FMC Hostname/IP',
        type: 'text',
        required: true,
        placeholder: 'fmc.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'domain',
        label: 'Domain',
        type: 'text',
        required: false,
        default: 'Global',
        placeholder: 'Global',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
      },
    ],
    docs_url: 'https://developer.cisco.com/docs/firepower/',
  },
  {
    id: 'fortinet',
    name: 'Fortinet FortiGate',
    category: 'Network Security',
    description: 'Connect to FortiGate firewalls and FortiManager for security policy and threat management.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'hostname',
        label: 'FortiGate/FortiManager Hostname',
        type: 'text',
        required: true,
        placeholder: 'fortigate.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Generate API key in System → Admin → Administrator',
      },
      {
        name: 'vdom',
        label: 'Virtual Domain (VDOM)',
        type: 'text',
        required: false,
        default: 'root',
        placeholder: 'root',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
      },
    ],
    docs_url: 'https://docs.fortinet.com/document/fortigate/latest/administration-guide/399023/rest-api-administrator',
  },
  {
    id: 'checkpoint',
    name: 'Check Point',
    category: 'Network Security',
    description: 'Integrate with Check Point firewalls and Security Management Server for threat prevention.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'management_server',
        label: 'Management Server',
        type: 'text',
        required: true,
        placeholder: 'checkpoint.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'domain',
        label: 'Domain',
        type: 'text',
        required: false,
        placeholder: 'SMC User',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://sc1.checkpoint.com/documents/latest/APIs/',
  },
  {
    id: 'zscaler',
    name: 'Zscaler',
    category: 'Network Security',
    description: 'Cloud-native security platform for secure internet and SaaS access (ZIA/ZPA).',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'cloud',
        label: 'Zscaler Cloud',
        type: 'select',
        required: true,
        options: [
          { value: 'zscaler.net', label: 'Zscaler.net' },
          { value: 'zscalerone.net', label: 'ZscalerOne.net' },
          { value: 'zscalertwo.net', label: 'ZscalerTwo.net' },
          { value: 'zscalerthree.net', label: 'ZscalerThree.net' },
          { value: 'zscloud.net', label: 'zsCloud.net' },
        ],
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://help.zscaler.com/zia/api',
  },
  {
    id: 'sophos',
    name: 'Sophos Firewall',
    category: 'Network Security',
    description: 'Sophos XG Firewall integration for unified threat management and network security.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'hostname',
        label: 'Firewall Hostname/IP',
        type: 'text',
        required: true,
        placeholder: 'sophos.example.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Generate in Sophos Firewall → Backup & Firmware → API',
      },
      {
        name: 'port',
        label: 'API Port',
        type: 'number',
        required: false,
        default: 4444,
        placeholder: '4444',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: false,
      },
    ],
    docs_url: 'https://docs.sophos.com/nsg/sophos-firewall/18.5/API/index.html',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'Network Security',
    description:
      'Cloudflare WAF, Zero Trust Gateway, and Access response actions, plus read-only IP/domain threat lookups. Lets Vigil propose and (with approval) execute WAF blocks, Gateway DNS/HTTP block policies, and Zero Trust session revocations.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText:
          'Create at Cloudflare → My Profile → API Tokens. Required scopes: Zone:Firewall Services:Edit, Account:Zero Trust:Edit, Account:Access:Edit, Account:Account Analytics:Read.',
      },
      {
        name: 'account_id',
        label: 'Account ID',
        type: 'text',
        required: false,
        helpText: 'Required for Zero Trust Gateway and Access actions.',
      },
      {
        name: 'zone_id',
        label: 'Default Zone ID',
        type: 'text',
        required: false,
        helpText:
          'Optional default zone for WAF rules. Individual actions may override this.',
      },
    ],
    docs_url: 'https://developers.cloudflare.com/api/',
  },
  {
    id: 'cloudforce_one',
    name: 'Cloudflare Cloudforce One',
    category: 'Threat Intelligence',
    description:
      'Cloudforce One STIX/TAXII 2.1 threat-intel feeds. Vigil polls configured collections, normalizes indicators, and enriches findings whose IOCs match. Operates independently of the Cloudflare WAF/Zero Trust integration so customers can subscribe to either or both.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText:
          'Cloudflare API token with Account:Cloudforce One:Read scope.',
      },
      {
        name: 'taxii_server_url',
        label: 'TAXII 2.1 Discovery URL',
        type: 'url',
        required: true,
        default: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/cloudforce-one/threat-events/taxii2/',
        placeholder: 'https://api.cloudflare.com/.../taxii2/',
        helpText:
          'TAXII 2.1 discovery endpoint. Substitute {account_id} with your Cloudflare account ID.',
      },
      {
        name: 'collection_ids',
        label: 'Collection IDs',
        type: 'text',
        required: true,
        placeholder: 'collection-uuid-1,collection-uuid-2',
        helpText:
          'Comma-separated list of TAXII collection IDs to poll. Leave empty to skip polling.',
      },
      {
        name: 'poll_interval_seconds',
        label: 'Poll Interval (seconds)',
        type: 'number',
        required: false,
        default: 900,
        helpText: 'How often Vigil pulls the latest indicators. Default 900 (15 min); minimum enforced server-side is 60.',
      },
    ],
    docs_url: 'https://developers.cloudflare.com/security-center/cloudforce-one/',
  },
  {
    id: 'juniper-srx',
    name: 'Juniper SRX',
    category: 'Network Security',
    description: 'Juniper SRX Series firewalls for enterprise network security and threat prevention.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'hostname',
        label: 'SRX Hostname/IP',
        type: 'text',
        required: true,
        placeholder: 'srx.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'port',
        label: 'SSH/NETCONF Port',
        type: 'number',
        required: false,
        default: 830,
        placeholder: '830',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.juniper.net/documentation/us/en/software/junos/netconf/index.html',
  },

  // INCIDENT MANAGEMENT
  {
    id: 'jira',
    name: 'Jira',
    category: 'Incident Management',
    description: 'Create and manage security incidents in Jira.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'url',
        label: 'Jira URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-domain.atlassian.net',
      },
      {
        name: 'username',
        label: 'Email/Username',
        type: 'text',
        required: true,
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Create API token at https://id.atlassian.com/manage-profile/security/api-tokens',
      },
      {
        name: 'project_key',
        label: 'Default Project Key',
        type: 'text',
        required: false,
        placeholder: 'SEC',
        helpText: 'Optional: Default project for creating issues',
      },
    ],
    docs_url: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/',
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    category: 'Incident Management',
    description: 'Enterprise incident and service management platform for tracking and managing security incidents.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'instance_url',
        label: 'ServiceNow Instance URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-instance.service-now.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'admin',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'assignment_group',
        label: 'Default Assignment Group',
        type: 'text',
        required: false,
        placeholder: 'Security Operations',
        helpText: 'Optional: Default group for incident assignment',
      },
    ],
    docs_url: 'https://docs.servicenow.com/bundle/tokyo-application-development/page/integrate/inbound-rest/concept/c_RESTAPI.html',
  },
  {
    id: 'thehive',
    name: 'TheHive',
    category: 'Incident Management',
    description: 'Open-source Security Incident Response Platform for SOC teams to investigate and respond to security incidents.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'url',
        label: 'TheHive Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://thehive.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Create API key in TheHive user settings',
      },
      {
        name: 'organization',
        label: 'Organization',
        type: 'text',
        required: false,
        placeholder: 'default',
        helpText: 'TheHive organization name (default: "default")',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.thehive-project.org/thehive/api-docs/',
  },
  {
    id: 'cortex-xsoar',
    name: 'Cortex XSOAR (Demisto)',
    category: 'Incident Management',
    description: 'Palo Alto Networks SOAR platform for security orchestration, automation, and incident response.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'server_url',
        label: 'XSOAR Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://xsoar.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Generate API key in XSOAR Settings → Integrations → API Keys',
      },
      {
        name: 'api_key_id',
        label: 'API Key ID',
        type: 'text',
        required: true,
        helpText: 'API Key ID from XSOAR',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://xsoar.pan.dev/docs/reference/api/common-server-python',
  },
  {
    id: 'swimlane',
    name: 'Swimlane',
    category: 'Incident Management',
    description: 'Low-code security automation and SOAR platform for incident response and case management.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'server_url',
        label: 'Swimlane Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://swimlane.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://swimlane.com/knowledge-center/docs/developer-guide/rest-api/',
  },
  {
    id: 'ibm-resilient',
    name: 'IBM Security QRadar SOAR',
    category: 'Incident Management',
    description: 'IBM Resilient (QRadar SOAR) platform for orchestrating and automating incident response processes.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'host',
        label: 'Resilient Host',
        type: 'url',
        required: true,
        placeholder: 'https://resilient.example.com',
      },
      {
        name: 'org_name',
        label: 'Organization Name',
        type: 'text',
        required: true,
        placeholder: 'YourOrg',
      },
      {
        name: 'api_key_id',
        label: 'API Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_key_secret',
        label: 'API Key Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://www.ibm.com/docs/en/sqr/latest?topic=overview-rest-api',
  },
  {
    id: 'opsgenie',
    name: 'Opsgenie',
    category: 'Incident Management',
    description: 'Atlassian incident management and alerting platform for on-call teams and incident coordination.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Create API integration in Opsgenie Settings → API key management',
      },
      {
        name: 'region',
        label: 'Region',
        type: 'select',
        required: true,
        default: 'us',
        options: [
          { value: 'us', label: 'US (api.opsgenie.com)' },
          { value: 'eu', label: 'EU (api.eu.opsgenie.com)' },
        ],
      },
    ],
    docs_url: 'https://docs.opsgenie.com/docs/api-overview',
  },

  // COMMUNICATIONS
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communications',
    description: 'Send security alerts and notifications to Slack channels.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'bot_token',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: 'xoxb-your-bot-token',
        helpText: 'Create a Slack app at https://api.slack.com/apps',
      },
      {
        name: 'default_channel',
        label: 'Default Channel',
        type: 'text',
        required: false,
        placeholder: '#security-alerts',
        helpText: 'Optional: Default channel for notifications',
      },
    ],
    docs_url: 'https://api.slack.com/tutorials',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    category: 'Communications',
    description: 'Create incidents and send alerts through PagerDuty for on-call management.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        placeholder: 'Your PagerDuty API token',
        helpText: 'Create API key at https://support.pagerduty.com/docs/api-access-keys',
      },
      {
        name: 'integration_key',
        label: 'Integration Key',
        type: 'password',
        required: true,
        placeholder: 'Service integration key',
        helpText: 'Events API v2 integration key for your service',
      },
      {
        name: 'default_urgency',
        label: 'Default Urgency',
        type: 'select',
        required: false,
        default: 'high',
        options: [
          { value: 'high', label: 'High' },
          { value: 'low', label: 'Low' },
        ],
      },
    ],
    docs_url: 'https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-events-api-v2-overview',
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    category: 'Communications',
    description: 'Send security alerts and notifications to Microsoft Teams channels.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'webhook_url',
        label: 'Webhook URL',
        type: 'password',
        required: true,
        placeholder: 'https://your-org.webhook.office.com/webhookb2/...',
        helpText: 'Create incoming webhook in Teams channel settings',
      },
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: false,
        placeholder: 'Azure AD tenant ID (optional)',
        helpText: 'Optional: For advanced Graph API integration',
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook',
  },
  {
    id: 'email',
    name: 'Email (SMTP)',
    category: 'Communications',
    description: 'Send security alerts via email using SMTP server.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'smtp_host',
        label: 'SMTP Host',
        type: 'text',
        required: true,
        placeholder: 'smtp.gmail.com',
      },
      {
        name: 'smtp_port',
        label: 'SMTP Port',
        type: 'number',
        required: true,
        default: 587,
        placeholder: '587',
      },
      {
        name: 'smtp_username',
        label: 'SMTP Username',
        type: 'text',
        required: true,
        placeholder: 'your-email@example.com',
      },
      {
        name: 'smtp_password',
        label: 'SMTP Password',
        type: 'password',
        required: true,
        placeholder: 'Your SMTP password or app-specific password',
      },
      {
        name: 'from_email',
        label: 'From Email Address',
        type: 'text',
        required: true,
        placeholder: 'security-alerts@example.com',
      },
      {
        name: 'default_recipients',
        label: 'Default Recipients',
        type: 'text',
        required: false,
        placeholder: 'soc@example.com, security@example.com',
        helpText: 'Comma-separated list of default email recipients',
      },
      {
        name: 'use_tls',
        label: 'Use TLS/STARTTLS',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://datatracker.ietf.org/doc/html/rfc5321',
  },
  {
    id: 'webhook',
    name: 'Generic Webhook',
    category: 'Communications',
    description: 'Send alerts to custom webhook endpoints for flexible integrations.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'webhook_url',
        label: 'Webhook URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-endpoint.com/webhook',
      },
      {
        name: 'authentication_type',
        label: 'Authentication Type',
        type: 'select',
        required: true,
        default: 'none',
        options: [
          { value: 'none', label: 'None' },
          { value: 'bearer', label: 'Bearer Token' },
          { value: 'basic', label: 'Basic Auth' },
          { value: 'api_key', label: 'API Key Header' },
        ],
      },
      {
        name: 'auth_token',
        label: 'Authentication Token/Key',
        type: 'password',
        required: false,
        placeholder: 'Token or API key (if required)',
      },
      {
        name: 'custom_headers',
        label: 'Custom Headers (JSON)',
        type: 'text',
        required: false,
        placeholder: '{"X-Custom-Header": "value"}',
        helpText: 'Optional: Additional headers as JSON object',
      },
    ],
    docs_url: 'https://webhook.site/#!/',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'Communications',
    description: 'Send security alerts to Discord channels via webhook.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'webhook_url',
        label: 'Webhook URL',
        type: 'password',
        required: true,
        placeholder: 'https://discord.com/api/webhooks/...',
        helpText: 'Create webhook in Discord channel settings → Integrations',
      },
      {
        name: 'username',
        label: 'Bot Username',
        type: 'text',
        required: false,
        default: 'Security Bot',
        placeholder: 'Security Bot',
      },
      {
        name: 'mention_role',
        label: 'Mention Role ID',
        type: 'text',
        required: false,
        placeholder: '123456789012345678',
        helpText: 'Optional: Role ID to mention for critical alerts',
      },
    ],
    docs_url: 'https://discord.com/developers/docs/resources/webhook',
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    category: 'Communications',
    description: 'Send security alerts to Mattermost channels (open-source Slack alternative).',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'webhook_url',
        label: 'Webhook URL',
        type: 'password',
        required: true,
        placeholder: 'https://your-mattermost.com/hooks/...',
        helpText: 'Create incoming webhook in Mattermost channel settings',
      },
      {
        name: 'default_channel',
        label: 'Default Channel',
        type: 'text',
        required: false,
        placeholder: 'security-alerts',
        helpText: 'Optional: Default channel for notifications',
      },
      {
        name: 'username',
        label: 'Bot Username',
        type: 'text',
        required: false,
        default: 'Security Bot',
      },
    ],
    docs_url: 'https://developers.mattermost.com/integrate/webhooks/incoming/',
  },

  // SANDBOX ANALYSIS
  {
    id: 'hybrid-analysis',
    name: 'Hybrid Analysis',
    category: 'Sandbox Analysis',
    description: 'Analyze suspicious files using Hybrid Analysis sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Get your API key from https://www.hybrid-analysis.com/my-account?tab=api-key',
      },
    ],
    docs_url: 'https://www.hybrid-analysis.com/docs/api/v2',
  },
  {
    id: 'joe-sandbox',
    name: 'Joe Sandbox',
    category: 'Sandbox Analysis',
    description: 'Analyze malware using Joe Sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'api_url',
        label: 'API URL',
        type: 'url',
        required: true,
        default: 'https://jbxcloud.joesecurity.org/api',
        helpText: 'Use https://jbxcloud.joesecurity.org/api for Joe Sandbox Cloud',
      },
    ],
    docs_url: 'https://www.joesecurity.org/joe-sandbox-cloud',
  },
  {
    id: 'anyrun',
    name: 'ANY.RUN',
    category: 'Sandbox Analysis',
    description: 'Interactive malware analysis using ANY.RUN sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Get your API key from https://any.run/api-documentation/',
      },
    ],
    docs_url: 'https://any.run/api-documentation/',
  },
  {
    id: 'cape-sandbox',
    name: 'CAPE Sandbox',
    category: 'Sandbox Analysis',
    description: 'Detonate files and URLs in a self-hosted CAPEv2 sandbox for behavioral analysis, IOCs, and PCAPs.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'url',
        label: 'CAPE URL',
        type: 'url',
        required: true,
        placeholder: 'https://cape.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'CAPEv2 REST API token, from your CAPE deployment.',
      },
    ],
    docs_url: 'https://capev2.readthedocs.io/en/latest/usage/api.html',
  },

  // FORENSICS & ANALYSIS
  {
    id: 'timesketch',
    name: 'Timesketch',
    category: 'Forensics & Analysis',
    description: 'Open-source forensic timeline analysis for collaborative investigations. Create and analyze timelines from security events.',
    functionality_type: 'Digital Forensics',
    has_ui: true,
    fields: [
      {
        name: 'server_url',
        label: 'Timesketch Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://timesketch.example.com',
        helpText: 'URL to your Timesketch server',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: false,
        placeholder: 'admin',
        helpText: 'Required if not using API token',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: false,
        helpText: 'Required if not using API token',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: false,
        helpText: 'Alternative to username/password authentication',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://timesketch.org/guides/user/basic-concepts/',
  },
  {
    id: 'velociraptor',
    name: 'Velociraptor',
    category: 'Forensics & Analysis',
    description: 'Advanced digital forensics and incident response tool for endpoint visibility and artifact collection.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'server_url',
        label: 'Velociraptor Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://velociraptor.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Generate API key in Velociraptor server configuration',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://docs.velociraptor.app/',
  },
  {
    id: 'grr',
    name: 'GRR Rapid Response',
    category: 'Forensics & Analysis',
    description: 'Google\'s incident response framework for remote live forensics and artifact collection.',
    fields: [
      {
        name: 'server_url',
        label: 'GRR Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://grr.example.com',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://grr-doc.readthedocs.io/en/latest/',
  },
  {
    id: 'autopsy',
    name: 'Autopsy',
    category: 'Forensics & Analysis',
    description: 'Digital forensics platform for investigating hard drives and smartphones (Sleuth Kit GUI).',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'server_url',
        label: 'Autopsy Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://autopsy.example.com',
        helpText: 'Autopsy collaborative server (if configured)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: false,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: false,
      },
    ],
    docs_url: 'https://sleuthkit.org/autopsy/docs/',
  },
  {
    id: 'osquery',
    name: 'osquery',
    category: 'Forensics & Analysis',
    description: 'SQL-powered operating system instrumentation for endpoint visibility and security monitoring.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'fleet_url',
        label: 'Fleet/Kolide Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://fleet.example.com',
        helpText: 'Fleet or Kolide server for osquery management',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://fleetdm.com/docs/using-fleet/rest-api',
  },
  {
    id: 'volatility',
    name: 'Volatility',
    category: 'Forensics & Analysis',
    description: 'Advanced memory forensics framework for extracting digital artifacts from RAM samples.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'workbench_url',
        label: 'Volatility Workbench URL',
        type: 'url',
        required: false,
        placeholder: 'https://volatility.example.com',
        helpText: 'Optional: URL to Volatility Workbench server (if deployed)',
      },
      {
        name: 'analysis_path',
        label: 'Memory Dump Storage Path',
        type: 'text',
        required: true,
        placeholder: '/forensics/memory-dumps',
        helpText: 'Shared path for memory dump analysis',
      },
      {
        name: 'profile_path',
        label: 'Volatility Profiles Path',
        type: 'text',
        required: false,
        placeholder: '/volatility/profiles',
        helpText: 'Path to custom Volatility profiles',
      },
    ],
    docs_url: 'https://volatility3.readthedocs.io/en/latest/',
  },
  {
    id: 'plaso',
    name: 'Plaso (log2timeline)',
    category: 'Forensics & Analysis',
    description: 'Super timeline generation tool for forensic artifact collection and timeline analysis.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'server_url',
        label: 'Plaso/Timesketch Server URL',
        type: 'url',
        required: false,
        placeholder: 'https://plaso.example.com',
        helpText: 'Optional: Central server for Plaso processing',
      },
      {
        name: 'storage_path',
        label: 'Plaso Storage Path',
        type: 'text',
        required: true,
        placeholder: '/forensics/plaso-storage',
        helpText: 'Path for storing Plaso dump files',
      },
      {
        name: 'workers',
        label: 'Number of Workers',
        type: 'number',
        required: false,
        default: 4,
        placeholder: '4',
        helpText: 'Parallel processing workers',
      },
    ],
    docs_url: 'https://plaso.readthedocs.io/en/latest/',
  },
  {
    id: 'rekall',
    name: 'Rekall',
    category: 'Forensics & Analysis',
    description: 'Memory forensic framework for incident response and malware analysis.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'analysis_path',
        label: 'Analysis Storage Path',
        type: 'text',
        required: true,
        placeholder: '/forensics/rekall',
        helpText: 'Path for Rekall analysis files',
      },
      {
        name: 'repository_url',
        label: 'Profile Repository URL',
        type: 'url',
        required: false,
        placeholder: 'https://github.com/google/rekall-profiles',
        helpText: 'URL to profile repository',
      },
    ],
    docs_url: 'http://www.rekall-forensic.com/documentation-1/rekall-documentation',
  },
  {
    id: 'yara',
    name: 'YARA',
    category: 'Forensics & Analysis',
    description: 'Pattern matching tool for malware identification and classification in forensic investigations.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'rules_repository',
        label: 'YARA Rules Repository',
        type: 'url',
        required: true,
        placeholder: 'https://github.com/your-org/yara-rules',
        helpText: 'Git repository containing YARA rules',
      },
      {
        name: 'local_rules_path',
        label: 'Local Rules Path',
        type: 'text',
        required: false,
        placeholder: '/yara/rules',
        helpText: 'Local path to YARA rules directory',
      },
      {
        name: 'auto_update',
        label: 'Auto-Update Rules',
        type: 'boolean',
        default: true,
        helpText: 'Automatically pull latest rules from repository',
      },
    ],
    docs_url: 'https://yara.readthedocs.io/en/stable/',
  },
  {
    id: 'cuckoo',
    name: 'Cuckoo Sandbox',
    category: 'Forensics & Analysis',
    description: 'Automated malware analysis system for dynamic behavioral analysis and forensic investigation.',
    functionality_type: 'Digital Forensics',
    fields: [
      {
        name: 'server_url',
        label: 'Cuckoo Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://cuckoo.example.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: false,
        helpText: 'Optional: API token if authentication is enabled',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://cuckoo.readthedocs.io/en/latest/',
  },

  // NETWORK TOPOLOGY FUSION
  {
    id: 'vstrike',
    name: 'CloudCurrent VStrike',
    category: 'Network Security',
    description:
      "Embed VStrike's network topology UI inside Vigil case investigations. Vigil drives which network and what kill-chain to play; VStrike streams the visualization back via WebSocket. Provides segment, criticality, mission-system, blast-radius, and attack-path enrichment to every Vigil agent.",
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'url',
        label: 'VStrike Base URL',
        type: 'url',
        required: true,
        placeholder: 'https://vstrike.net',
        helpText: 'Base URL of your VStrike deployment.',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'deeptempo_manager',
        helpText:
          'VStrike account username. Vigil exchanges username + password for a JWT via /mcp-login and refreshes it automatically — no API key paste needed.',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
        placeholder: 'Password for the VStrike account',
        helpText:
          'VStrike account password. Stored encrypted at ~/.vigil/secrets.enc — never written to disk in plaintext.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
    ],
    docs_url: 'https://cloudcurrent.biz/vstrike',
  },
]

export const INTEGRATION_CATEGORIES = [
  'Reference / Platform',
  'Threat Intelligence',
  'EDR/XDR',
  'SIEM',
  'Data Pipeline',
  'Cloud Security',
  'Identity & Access',
  'Network Security',
  'Incident Management',
  'Communications',
  'Sandbox Analysis',
  'Forensics & Analysis',
  'Custom',
]

// Custom integrations loaded dynamically
let customIntegrations: IntegrationMetadata[] = []

// Combined integrations (built-in + custom)
let allIntegrations: IntegrationMetadata[] = [...INTEGRATIONS]

/**
 * Load custom integrations from the backend
 */
export async function loadCustomIntegrations(): Promise<void> {
  try {
    const response = await fetch(`${basePath}/api/custom-integrations/list`, {
      credentials: 'include',
    })
    const data = await response.json()
    
    if (data.success && data.integrations) {
      customIntegrations = data.integrations.map((metadata: any) => ({
        ...metadata,
        is_custom: true,
      }))
      
      // Merge with built-in integrations
      allIntegrations = [...INTEGRATIONS, ...customIntegrations]
      
      console.log(`Loaded ${customIntegrations.length} custom integrations`)
    }
  } catch (error) {
    console.error('Error loading custom integrations:', error)
    customIntegrations = []
    allIntegrations = [...INTEGRATIONS]
  }
}

/**
 * Get all integrations (built-in + custom)
 */
export function getAllIntegrations(): IntegrationMetadata[] {
  return allIntegrations
}

